# Generated by Django 4.1.7 on 2023-02-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='product/Image'),
        ),
    ]
